### ISSUE TITLE
List of notebook cells that run too long for the workshop

### ISSUE THREAD

**Issue by rbavery** [developmentseed/servir-amazonia-ml#6]
These notebook cells take a long time (over ten minutes or close to 10 minutes) to run in Google Colab and we should probably flag these or find a way around not running them during the workshop.

I think our strategy is going to be switching to the jupyter book html to discuss these long running cells. This requires us to make sure any variables that are created in these cells can be loaded from files quickly after discussing the long running outputs that are prebuilt in the html @lillythomas :

Lesson 3
- [ ] # Check for values in train, val, and test partitions in Lesson3_deeplearning_crop_segmentation.ipynb (we can just flag that this shouldn't be run and turn it into markdown)
- [ ] Visualize the Data, which starts with 
```
# select only for tiles with foreground labels present
foreground_list_x = []
foreground_list_y = []
```

**Comment by lillythomas** [comment]
Yeah some of these are still on the longer side...good call on the mark down, and thanks for flagging this.

**Comment by lillythomas** [comment]
`Visualize the Data` has been fixed by using the background tiles list as a filter instead of PIL @rbavery

**Comment by rbavery** [comment]
I tried running that cell just now on colab and I get this error:

Input/output error: '/content/gdrive/My Drive/servir-tf-devseed/indices/tile_terrabio_15835.png'

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-12-1ae73e799c59> in <module>()
     31 
     32   plt.subplot(display_num, 2, i + 1)
---> 33   plt.imshow(mpimg.imread(x_pathname))
     34   plt.title("Original Image")
     35 

3 frames
/usr/local/lib/python3.7/dist-packages/matplotlib/cbook/__init__.py in to_filehandle(fname, flag, return_opened, encoding)
    401             fh = bz2.BZ2File(fname, flag)
    402         else:
--> 403             fh = open(fname, flag, encoding=encoding)
    404         opened = True
    405     elif hasattr(fname, 'seek'):

OSError: [Errno 5] Input/output error: '/content/gdrive/My Drive/servir-tf-devseed/indices/tile_terrabio_15835.png'
```

when I try to check if this file exists I get disconnected
`os.path.isfile("/content/gdrive/My Drive/servir-tf-devseed/indices/tile_terrabio_15835.png")`

**Comment by rbavery** [comment]
just tried again and I ran into the same error with a different file. when I reconnected and re-ran, I was able to run the cell, so maybe this is just what we ask workshop participants to do if it comes up.

**Comment by rbavery** [comment]
For the multi-image example for saving predictions, I'm unable to save predictions

```python
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: /content/gdrive/My Drive/servir-tf-devseed/predictions_test_focal_loss/tile_terrabio_21138.png is a low contrast image
  """Entry point for launching an IPython kernel.
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
<ipython-input-96-aa3a088fd808> in <module>()
----> 1 skio.imsave(os.path.join(tiled_prediction_dir, "{}.png".format(basename)), pred_mask)

8 frames
/usr/local/lib/python3.7/dist-packages/imageio/core/request.py in get_file(self)
    340         elif self._uri_type == URI_FILENAME:
    341             if want_to_write:
--> 342                 self._file = open(self.filename, "wb")
    343             else:
    344                 self._file = open(self.filename, "rb")

PermissionError: [Errno 1] Operation not permitted: '/content/gdrive/My Drive/servir-tf-devseed/predictions_test_focal_loss/tile_terrabio_21138.png'
```

**Comment by lillythomas** [comment]
Yeah the `Visualize the Data` sometimes disconnects on I/O in that way for me too, but runs again after one or more tries. It's annoying and I can't pin down why it's happening. 

As for the prediction write out, I think it is because I already have a folder in the shared drive titled `predictions_test_focal_loss ` and it won't let folks overwrite it. I meant to delete it, so that this would work:
```
tiled_prediction_dir = os.path.join(root_dir,'predictions_test_focal_loss/')
if not os.path.exists(tiled_prediction_dir):
    os.makedirs(tiled_prediction_dir)
```
for each participant in their shortcut path and the files would write out there. 

I will delete the folder with that name from the shared drive so that the folder actually is made under that name when participants run the notebook.

**Comment by lillythomas** [comment]
@rbavery I made a [PR](https://github.com/developmentseed/servir-amazonia-ml/pull/21) to load and plot the examples from 3 sample pathnames rather than from randomization. I reserved the randomized loading code as mark down instead of executable code though.
